# Generated by Django 5.2.15 on 2026-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_name_when_project_null_and_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', True)), fields=('workspace', 'name'), name='unique_workspace_name_when_project_null_and_not_deleted'),
        ),
    ]
