# Generated by Django 5.2.15 on 2026-08-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(condition=models.Q(('is_global', True)), fields=['workspace', 'is_global'], name='page_workspace_global_idx'),
        ),
    ]
